#include <SDL3/SDL.h>
#include <core/Core.hpp>
#include <core/Resources.hpp>
#include <fstream>
#include <core/IO/IO.hpp>
#include <gfx/Pass.hpp>
#include <gfx/Pipeline.hpp>
#include <gfx/gfx.hpp>
#include <iostream>
#include <string>
#include <vector>

int main(int argc, char **argv)
{
    pixl::core::Core::Init(pixl::core::CoreInitData{});
    pixl::gfx::GfxInitData gfxInit{};
    gfxInit.windowFlags = SDL_WINDOW_RESIZABLE;
    if (pixl::gfx::Gfx::Init(gfxInit) != 0)
    {
        return -1;
    }

    auto *window = pixl::gfx::Gfx::GetWindow();
    auto *gpu = pixl::gfx::Gfx::GetGpu();

    // Try to load simple SPIR-V shaders if present (from disk or mounted paks).
    auto loadFile = [](const std::string &path) -> std::vector<char>
    {
        return pixl::core::io::IO::ReadFileToBuffer(path);
    };

    // Expect SPIR-V generated by xmake shader rule; search common shader folders.
    auto loadSpv = [&](const std::string &name) -> std::vector<char>
    {
        std::vector<std::string> candidates;

        candidates.push_back("shaders/" + name);
        candidates.push_back("build/shaders/" + name);
        candidates.push_back("build/mingw/x86_64/debug/shaders/" + name);
        candidates.push_back("build/mingw/x86_64/release/shaders/" + name);
        candidates.push_back("resources/shaders/" + name);

        for (const auto &c : candidates)
        {
            auto data = loadFile(c);
            if (!data.empty())
            {
                std::cout << "Loaded shader: " << c << " (size: " << data.size() << " bytes)" << std::endl;
                return data;
            }
        }
        return {};
    };

    const pixl::core::ResourceManifest *manifest = pixl::core::Resources::GetManifest();
    if (manifest && !manifest->entryScene.empty())
    {
        std::cout << "Manifest entry scene: " << manifest->entryScene << std::endl;
    }
    if (manifest && !manifest->startupScripts.empty())
    {
        std::cout << "Startup scripts: ";
        for (const auto &s : manifest->startupScripts)
        {
            std::cout << s << " ";
        }
        std::cout << std::endl;
    }

    std::vector<char> vsData;
    std::vector<char> fsData;

    if (manifest && manifest->shaders.size() >= 2)
    {
        vsData = loadSpv(manifest->shaders[0]);
        fsData = loadSpv(manifest->shaders[1]);
    }
    else
    {
        vsData = loadSpv("triangle.vert.spv");
        if (vsData.empty())
            vsData = loadSpv("triangle.vert.glsl.spv");
        fsData = loadSpv("triangle.frag.spv");
        if (fsData.empty())
            fsData = loadSpv("triangle.frag.glsl.spv");
    }

    pixl::gfx::ShaderHandle vsHandle = pixl::gfx::InvalidHandle;
    pixl::gfx::ShaderHandle fsHandle = pixl::gfx::InvalidHandle;
    pixl::gfx::PipelineHandle pipeline = pixl::gfx::InvalidHandle;
    pixl::gfx::BufferHandle vbHandle = pixl::gfx::InvalidHandle;
    pixl::gfx::BufferHandle ibHandle = pixl::gfx::InvalidHandle;

    if (!vsData.empty() && !fsData.empty())
    {
        std::cout << "Creating shaders..." << std::endl;
        pixl::gfx::ShaderDesc vsDesc{};
        vsDesc.stages.push_back({pixl::gfx::ShaderStage::Vertex, pixl::gfx::ShaderLanguage::SPV, "main",
                                 std::string(vsData.data(), vsData.size())});
        pixl::gfx::ShaderDesc fsDesc{};
        fsDesc.stages.push_back({pixl::gfx::ShaderStage::Fragment, pixl::gfx::ShaderLanguage::SPV, "main",
                                 std::string(fsData.data(), fsData.size())});

        vsHandle = gpu->CreateShader(vsDesc);
        fsHandle = gpu->CreateShader(fsDesc);
        std::cout << "Shader handles: VS=" << vsHandle << " FS=" << fsHandle << std::endl;

        if (vsHandle != pixl::gfx::InvalidHandle && fsHandle != pixl::gfx::InvalidHandle)
        {
            struct Vertex
            {
                float pos[2];
                float color[3];
            };

            Vertex verts[] = {
                {{0.0f, -0.5f}, {1.0f, 0.0f, 0.0f}},
                {{0.5f, 0.5f}, {0.0f, 1.0f, 0.0f}},
                {{-0.5f, 0.5f}, {0.0f, 0.0f, 1.0f}},
            };
            uint16_t indices[] = {0, 1, 2};

            pixl::gfx::BufferDesc vbDesc{};
            vbDesc.size = sizeof(verts);
            vbDesc.usage = pixl::gfx::BufferUsage::Vertex;
            vbDesc.stride = sizeof(Vertex);
            vbHandle = gpu->CreateBuffer(vbDesc, verts, sizeof(verts));

            pixl::gfx::BufferDesc ibDesc{};
            ibDesc.size = sizeof(indices);
            ibDesc.usage = pixl::gfx::BufferUsage::Index;
            ibDesc.stride = sizeof(uint16_t);
            ibHandle = gpu->CreateBuffer(ibDesc, indices, sizeof(indices));

            pixl::gfx::GraphicsPipelineDesc pDesc{};
            pDesc.vertexShader = vsHandle;
            pDesc.fragmentShader = fsHandle;
            pDesc.primitive = pixl::gfx::PrimitiveType::TriangleList;
            pDesc.depthTest = false;
            pDesc.depthWrite = false;

            pixl::gfx::VertexBufferLayout bufLayout{};
            bufLayout.stride = sizeof(Vertex);
            bufLayout.rate = pixl::gfx::VertexInputRate::PerVertex;

            pixl::gfx::VertexAttribute attrPos{};
            attrPos.location = 0;
            attrPos.bufferSlot = 0;
            attrPos.format = pixl::gfx::VertexFormat::Float2;
            attrPos.offset = 0;

            pixl::gfx::VertexAttribute attrCol{};
            attrCol.location = 1;
            attrCol.bufferSlot = 0;
            attrCol.format = pixl::gfx::VertexFormat::Float3;
            attrCol.offset = sizeof(float) * 2;

            pDesc.vertexLayout.buffers.push_back(bufLayout);
            pDesc.vertexLayout.attributes.push_back(attrPos);
            pDesc.vertexLayout.attributes.push_back(attrCol);

            pipeline = gpu->CreateGraphicsPipeline(pDesc);
            std::cout << "Pipeline handle: " << pipeline << std::endl;
        }
        else
        {
            std::cout << "Failed to create shaders, SDL error: " << SDL_GetError() << std::endl;
        }
    }

    int frameCount = 0;
    bool running = true;
    while (running && frameCount < 300)
    {
        window->PollEvents();
        running = !window->ShouldClose();

        float t = frameCount / 3000.0f;
        pixl::gfx::RenderPassDesc pass{};
        pass.clearColorValue[0] = 0.1f + 0.3f * t;
        pass.clearColorValue[1] = 0.2f + 0.5f * (1.0f - t);
        pass.clearColorValue[2] = 0.3f;
        pass.clearColorValue[3] = 1.0f;

        if (gpu->BeginPass(pass) == 0)
        {
            if (pipeline != pixl::gfx::InvalidHandle && vbHandle != pixl::gfx::InvalidHandle && ibHandle != pixl::gfx::InvalidHandle)
            {
                if (gpu->BindPipeline(pipeline))
                {
                    gpu->BindVertexBuffer(vbHandle, 0, 0);
                    gpu->BindIndexBuffer(ibHandle, true, 0);
                    gpu->DrawIndexed(3, 0, 1, 0);
                }
            }
            gpu->EndPass();
        }
        else
        {
            std::cout << "BeginPass failed, stopping loop." << std::endl;
            break;
        }

        SDL_Delay(16);
        ++frameCount;
    }

    pixl::gfx::Gfx::Quit();
    pixl::core::Core::Quit();
    return 0;
}
