name: Build on Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2

    - name: Build project
      run: |
        make

    - name: Save artifacts
      run: |
        mkdir -p artifacts
        cp -r * artifacts/
      # Pour conserver le contenu généré dans les artifacts, y compris le répertoire "artifacts"
      if: always()

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifacts
        path: artifacts
      if: always()
