name: Build on Windows

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install mingw-w64
      run: |
        sudo apt update
        sudo apt install -y mingw-w64

    - name: Build project
      run: |
        make
