name: Build on Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2

    - name: Build project
      run: |
        make


    - name: Archive repository
      uses: actions/upload-artifact@v2
      with:
        name: repository-artifact
        path: .  # This archives the entire repository
